"""empty message

Revision ID: 4d01a84807d1
Revises: a6ceb33ee507
Create Date: 2023-07-22 02:44:55.399815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d01a84807d1'
down_revision = 'a6ceb33ee507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=100), nullable=False))
        batch_op.drop_column('fitbit_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitbit_user_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
