"""empty message

Revision ID: 9c08506d4929
Revises: 0958a2fef133
Create Date: 2023-07-24 14:28:33.583735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c08506d4929'
down_revision = '0958a2fef133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_user_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('patient_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('user_id')
        batch_op.drop_column('logical_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logical_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('patient_id')
        batch_op.drop_column('platform')
        batch_op.drop_column('platform_user_id')

    # ### end Alembic commands ###
