"""empty message

Revision ID: bf42eba0a256
Revises: 4d01a84807d1
Create Date: 2023-07-22 03:03:05.951358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf42eba0a256'
down_revision = '4d01a84807d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('expires_in',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('scope',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('scope',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('expires_in',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
